# Makefile for documentation
# minichem project
# Alexander Oleynichenko, 2016
# alexvoleynichenko@gmail.com

TEX=pdflatex
SRC=manual_ru.tex
CLEAN=rm *.{out,log,aux}

all:
	pdflatex $(SRC)

clean:
	$(CLEAN)

