#ifndef _MINICHEM_H_INCLUDED
#define _MINICHEM_H_INCLUDED

#define MINICHEM_VERSION "0.1"
#define MINICHEM_BUILD_DATE __DATE__
#define MINICHEM_BUILD_TIME __TIME__
//#define MINICHEM_BUILD_COMPILER 

#endif // _MINICHEM_H_INCLUDED
